export const testimonials = [
  {
    name: "Ali Guedda",
    role: "Senior Software Engineer @Leyton",
    text: "I had the pleasure of working with Hamza for two years. He is a passionate JavaScript enthusiast and a technophile who quickly adopts new technologies.\n\nHamza demonstrates extreme dedication in his work and is fully committed to completing his projects.",
    link: "https://linkedin.com/in/ali-guedda",
    profileImg: "ali.jpeg",
  },
  {
    name: "Abderrazzak Bajjou",
    role: "ML Engineer | Blockchain Enthusiast",
    text: "Hamza Mellahi co-founded FileQA with me, serving as our full-stack developer.\n\nHe skillfully built both the front-end and back-end of the platform, ensuring a seamless user experience.\n\nAlways available and easy to work with, Hamza's dedication and technical expertise were critical to our success.\n\nI highly recommend him for any future endeavors.",
    link: "https://www.linkedin.com/in/abderrazzak-bajjou/",
    profileImg: "zak.jpeg",
  },
  {
    name: "El Houssain INANI",
    role: "Staff Engineer @Leyton",
    text: "I worked with Hamza on different projects and in different teams, and he managed to bring brilliant ideas to deliver a valuable product.\n\nHe is excellent in the frontend area, but he isn't intimidated by backend concepts.\nIn fact, he solved many issues related to that. Having him on your team is a big advantage.",
    link: "https://www.linkedin.com/in/inanielhoussain/",
    profileImg: "houssain.jpeg",
  },
  {
    name: "Abdelilah Lbardi",
    role: "Senior Software Engineer @Leyton",
    text: "Hamza and I worked in different teams.\n\nHowever, we had the opportunity to exchange ideas about many technical challenges throughout my time at Leyton.\n\nI firmly believe that he would be a great asset to your company if you're looking for a frontend/full-stack engineer with deep expert knowledge of TypeScript, React, and Node.js.",
    link: "https://linkedin.com/in/abdelilahlbardi",
    profileImg: "abdelilah.jpeg",
  },
  {
    name: "Othman Charai",
    role: "Software Engineer @YouCan",
    text: "Hamza is a JavaScript and React expert who thrives on challenges. He consistently impresses me with his deep technical knowledge and problem-solving skills.\n\nHamza communicates with clarity, always backing his ideas with facts and practical solutions.\nHis passion for web development and ability to tackle complex issues make him an invaluable asset to any team.",
    link: "https://www.linkedin.com/in/othman-charai-620590200/",
    profileImg: "othmane.jpeg",
  },
  {
    name: "Noura EL Allam",
    role: "Software Engineer @Odoo",
    text: "Hamza is a former classmate with whom I have collaborated on several projects.\n\nI highly recommend him and trust his ability to deliver quality work.",
    link: "https://linkedin.com/in/flaredev",
    profileImg: "noura.jpeg",
  },
  {
    name: "Te-Chia Yu",
    role: "Founder @PostSale",
    text: "I highly recommend Hamza. He is responsible and a proactive team player.",
    link: "https://www.linkedin.com/in/davidyu37/",
    profileImg: "techia.jpeg",
  },
  {
    name: "A Fiverr Client",
    text: "Very fast and accurate in work. A+++++++++++",
  },
];
