export const testimonials = [
  {
    name: "Ali Guedda",
    role: "Senior Software Engineer @Leyton",
    text: "I had the pleasure of working with Hamza for two years, he is a passionate JavaScript enthusiast and a technophile who quickly adopts new technologies.\n\nHamza demonstrates extreme dedication in his work, fully committed to completing his projects.",
    link: "https://linkedin.com/in/ali-guedda",
    profileImg: "ali.jpeg",
  },
  {
    name: "Abderrazzak Bajjou",
    role: "ML Engineer | Blockchain Enthusiast",
    text: "Hamza Mellahi co-founded FileQA with me, serving as our full-stack developer.\nHe skillfully built both the front-end and back-end of the platform, ensuring a seamless user experience. \nAlways available and easy to work with, Hamza's dedication and technical expertise were critical to our success.\nI highly recommend him for any future endeavors.",
    link: "https://www.linkedin.com/in/abderrazzak-bajjou/",
    profileImg: "zak.jpeg",
  },
  {
    name: "El Houssain INANI",
    role: "Staff engineer @Leyton",
    text: "Hamza is a former classmate with whom I have collaborated on several projects, I highly recommend him and trust his ability to deliver quality work.",
    link: "https://www.linkedin.com/in/inanielhoussain/",
    profileImg: "houssain.jpeg",
  },
  {
    name: "Abdelilah Lbardi",
    role: "Senior Software Engineer @Leyton",
    text: "Hamza and I worked in different teams. \n\nHowever, we had the opportunity to exchange about lot of technical challenges throughout my time here at Leyton.\n\nI firmly believe that he can be a good asset to your company in case you're looking for frontend/full-stack engineer with deep experts knowledge of Typescript, React, and Nodejs.",
    link: "https://linkedin.com/in/abdelilahlbardi",
    profileImg: "abdelilah.jpeg",
  },
  {
    name: "Othman Charai",
    role: "Software Engineer @YouCan",
    text: "Hamza is a JavaScript and React expert who thrives on challenges. He consistently impresses with his deep technical knowledge and problem-solving skills.\n\n Hamza communicates with clarity, always backing his ideas with facts and practical solutions.\nHis passion for web development and ability to tackle complex issues make him an invaluable asset to any team.",
    link: "https://www.linkedin.com/in/othman-charai-620590200/",
    profileImg: "othmane.jpeg",
  },
  {
    name: "Noura EL Allam",
    role: "Senior Software Engineer @Odoo",
    text: "Hamza is a former classmate with whom I have collaborated on several projects, I highly recommend him and trust his ability to deliver quality work.",
    link: "https://linkedin.com/in/flaredev",
    profileImg: "noura.jpeg",
  },
  // {
  //   name: "Marwane Chaoui",
  //   role: "Sr. Software Engineer @Leyton | PHP / Node.js",
  //   text: "Hamza is a former classmate with whom I have collaborated on several projects, I highly recommend him and trust his ability to deliver quality work.",
  //   link: "https://www.linkedin.com/in/moghwan/",
  //   profileImg: "marwane.jpeg",
  // },
  {
    name: "Te-Chia Yu",
    role: "Founder @PostSale",
    text: "Highly recommend Hamza. Responsible and a proactive team player.",
    link: "https://www.linkedin.com/in/davidyu37/",
    profileImg: "techia.jpeg",
  },
  {
    name: "A Fiverr Client",
    text: "Very fast and accurate in working A+++++++++++",
  },
];
